services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # UI web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cicflowmeter:
    build: ./CICFlowMeter
    depends_on:
      - rabbitmq    
    volumes:
      - ./CICFlowMeter/pcaps:/pcaps
      - ./CICFlowMeter/flows:/flows
    environment:
      - PCAPS_DIR=/pcaps
      - FLOWS_DIR=/flows
      - DELAY=5
      - CONVERT_LINKTYPE=1

  oraculo:
    build: ./Oraculo
    depends_on:
      - cicflowmeter
      - elasticsearch
      - logstash
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 8g

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"  # Beats input
      - "9600:9600"  # Monitoring API
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

volumes:
  esdata: