global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  # Pull from Pushgateway (the easiest 'push' pattern)
  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
      
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8439"]

